### PR TITLE
pr

### PR DESCRIPTION
**Pull request by Astridxx**

### CODE REVIEW

**Comment by GiaSen** [comment]
Why that audio revert?

**Comment by GiaSen** [comment]
Package should be like this, and works
https://review.lineageos.org/c/LineageOS/android_device_zuk_msm8996-common/+/259716

**Comment by Astridxx** [comment]
> Why that audio revert?

01-19 01:55:17.389 E/audio_route(  769): Control 'LSM6 Mixer 
TERT_MI2S_TX' doesn't exist - skipping
01-19 01:55:17.389 E/audio_route(  769): Control 'LSM7 Mixer 
TERT_MI2S_TX' doesn't exist - skipping
01-19 01:55:17.389 E/audio_route(  769): Control 'LSM8 Mixer 
TERT_MI2S_TX' doesn't exist - skipping
01-19 01:55:17.391 E/audio_route(  769): Control 'LSM6 Mixer 
TERT_MI2S_TX' doesn't exist - skipping
01-19 01:55:17.391 E/audio_route(  769): Control 'LSM7 Mixer 
TERT_MI2S_TX' doesn't exist - skipping
01-19 01:55:17.391 E/audio_route(  769): Control 'LSM8 Mixer 
TERT_MI2S_TX' doesn't exist - skipping
01-19 01:55:17.392 E/audio_route(  769): Control 'LSM6 Mixer 
TERT_MI2S_TX' doesn't exist - skipping
01-19 01:55:17.392 E/audio_route(  769): Control 'LSM7 Mixer 
TERT_MI2S_TX' doesn't exist - skipping
01-19 01:55:17.393 E/audio_route(  769): Control 'LSM8 Mixer 
TERT_MI2S_TX' doesn't exist - skipping
01-19 01:55:17.393 E/audio_route(  769): Path name 
'listen-voice-wakeup-1 preproc' already exists
01-19 01:55:17.393 E/audio_route(  769): path created failed, please 
check the path if existed
01-19 01:55:17.393 E/audio_route(  769): Path name 
'listen-voice-wakeup-2 preproc' already exists
01-19 01:55:17.393 E/audio_route(  769): path created failed, please 
check the path if existed
01-19 01:55:17.393 E/audio_route(  769): Path name 
'listen-voice-wakeup-3 preproc' already exists
01-19 01:55:17.393 E/audio_route(  769): path created failed, please 
check the path if existed
01-19 01:55:17.393 E/audio_route(  769): Path name 
'listen-voice-wakeup-4 preproc' already exists
01-19 01:55:17.393 E/audio_route(  769): path created failed, please 
check the path if existed
01-19 01:55:17.393 E/audio_route(  769): Path name 
'listen-voice-wakeup-5 preproc' already exists
01-19 01:55:17.393 E/audio_route(  769): path created failed, please 
check the path if existed
01-19 01:55:17.393 E/audio_route(  769): Path name 
'listen-voice-wakeup-6 preproc' already exists
01-19 01:55:17.393 E/audio_route(  769): path created failed, please 
check the path if existed
01-19 01:55:17.394 E/audio_route(  769): Control 'LSM6 Mixer 
TERT_MI2S_TX' doesn't exist - skipping
01-19 01:55:17.394 E/audio_route(  769): Path name 
'listen-voice-wakeup-7 preproc' already exists
01-19 01:55:17.394 E/audio_route(  769): path created failed, please 
check the path if existed
01-19 01:55:17.394 E/audio_route(  769): Control 'LSM7 Mixer 
TERT_MI2S_TX' doesn't exist - skipping
01-19 01:55:17.394 E/audio_route(  769): Path name 
'listen-voice-wakeup-8 preproc' already exists
01-19 01:55:17.394 E/audio_route(  769): path created failed, please 
check the path if existed
01-19 01:55:17.394 E/audio_route(  769): Control 'LSM8 Mixer 
TERT_MI2S_TX' doesn't exist - skipping
01-19 01:55:17.395 E/audio_route(  769): Control 'ADC1_INP1 Switch' 
doesn't exist - skipping
01-19 01:55:17.395 E/audio_route(  769): Path name 
'listen-ape-handset-mic-preproc' already exists
01-19 01:55:17.395 E/audio_route(  769): path created failed, please 
check the path if existed
01-19 01:55:17.395 E/audio_route(  769): Path name 
'listen-ape-handset-dmic' already exists
01-19 01:55:17.395 E/audio_route(  769): path created failed, please 
check the path if existed

This error present

**Comment by Astridxx** [comment]
> Package should be like this, and works
> https://review.lineageos.org/c/LineageOS/android_device_zuk_msm8996-common/+/259716

See this
https://github.com/LineageOS/android_vendor_qcom_opensource_power/commit/434acc2ab4bab9d2407e5167be1dc2c22bfead0f

**Comment by GiaSen** [comment]
Okay, thanks

**Pull request merged**
